### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by cshnik** [cshnik/TaskSpace#1]
test description

**Comment by cshnik** [comment]
test closed

**Comment by Drugoy** [comment]
Этот issue tracker поддерживает метки (тэги), которые можно не назначать различным тикетам.
Метки можно создавать новые. Советую добавить несколько новых, для, например, разграничения приоритета: low priority, medium priority, high priority, critical + какую-нибудь arguable или discussion чтобы отмечать ими те тикеты, в которых ведётся обсуждение, или которые требуют какого-то решения, но хочется добиться консенсуса с пользователями, которые могли предложить что-то, что лично вам не очень понравилось, но пользователь продолжает защищать предложенную идею, приводя разумные доводы/аргументы в пользу предложенного.

**Comment by Drugoy** [comment]
Такая метка подошла бы для issue #9, в котором из нашего с вами обсуждения проблемы конкретного неподдерживаемого приложения вылился новый вопрос о принципе работы с такими приложениями: стоит ли их заносить в чёрный список и не работать с ними совсем или же дать пользователю выбор.

Даже если issue будет закрыто (если, например, какое-то решение было принято), то у него останется эта метка (issue же может быть и переоткрыто позже, если решение изменится).
