### ISSUE TITLE
[Critical] TaskSpace may hang the shell completely

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#10]
STR:
1. Open a new TaskSpace frame.
2. Open an unsupported application (for example Microsoft Office 2010 Word).
3. Drag'n'drop the unsupported application's window onto TaskSpace's frame.
[An error shows up]
4. Dick around the windows. Try to reproduce the above steps without closing the error's window.

Expected result:
Unsupported app remains in the separate window and everything is fine, except that b

Actual result:
TaskSpace's frame partly consumes the unsupported application's window. The unsupported application's window becomes unresponive and may make hang the whole WinExplorer shell (the cursor becomes a circle going rounds and the clicks anywhere - get ignored.
This is how it looks:
<img src="https://i.imgur.com/aSSQUu5.png">
<img src="https://i.imgur.com/8poEaKh.png">

This issue is related to issue #9 and all the unsupported applications.

**Comment by cshnik** [comment]
Fixed in v0.1.5.3.
