### ISSUE TITLE
[Locale] make "language" menu item non-localized (always "language") and it's sub-items in English

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#11]
The thing is that user may accidentally switch program's language to the one he completely doesn't know and may later have problems switching it back.

It is known to be a good practice to always use English for language switching menu.
And you also should either always use english names for all the languages or make those menuitems' text static, so users will always see "English" and "Русский" irregardless of currently selected language.

**Comment by cshnik** [comment]
Agreed. I think the second choice to use native labels(English, Русский) is the best one.

**Comment by cshnik** [comment]
Fixed in v0.1.5.3.
