### ISSUE TITLE
[FR] add "new tab" button to frame's tab bar

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#13]
Currently, the process of creating new frames and then binding them takes pretty much time.
I suggest to add "new tab" button to the tab bar to quickly create a new empty tab in the same frame.

**Comment by cshnik** [comment]
There is an exisiting option "Create TaskSpace as Tab" in the system menu (right click on the frame's caption).

**Comment by Drugoy** [comment]
Oh, I didn't know that. Although I'd still prefer 1 click instead of 2.
Yet, feel free to close this issue.

**Comment by cshnik** [comment]
Closed as already implemented.

**Comment by Drugoy** [comment]
Please add "Denied" or "Wontfix" label to this issue.
