### ISSUE TITLE
[FR] add hotkeys for navigation between tabs and between windows in a tab

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#14]
I think it's a pity that there's no way to navigate between tabs and between windows in a tab.

I suggest to add hotkeys for:
a. switching between tabs in the active frame (forward and backward switching).
b. switching between windows in the active tab (forward and backward switching).

It's better to make hotkeys user-configurable, and I suggest these as default:
a. CapsLock+Tab for forward switching between tabs in the active frame.
b. CapsLock+Shift+Tab for backward switching between tabs in the active frame.
c. Ctrl+CapsLock+Tab for forward switching between windows in the active tab of the active frame.
d. Ctrl+CapsLock+Shift+Tab for backward switching between windows in the active tab of the active frame.

**Comment by cshnik** [comment]
The list of hotkeys hardcoded in TaskSpace v0.2.0.0:
Global Windows hotkeys:
Ctrl+Alt+T     - create new TaskSpace
Ctrl+Shift+T  - create new TaskSpace, attached current window
Ctrl+Shift+M - move current window to last active TaskSpace
TaskSpace hotkeys:
Ctrl+T         - add new tab
Ctrl+0...9     - activate corresponding tab by index

**Comment by Drugoy** [comment]
Hardcoded hotkeys always suck :(
