### ISSUE TITLE
[FR] add "scroll over tab bar to switch tabs" feature

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#15]
I suggest to add a way of switching tabs in a frame (irregardless whether it's currently active one or not) by mouse scroll, if the cursor points anywhere on tab-bar of a frame.

**Comment by cshnik** [comment]
Fixed in v0.1.5.3.

**Comment by Drugoy** [comment]
Seems to work fine, except I forgot that this feature usually needs 2 options to be more comfortable for everyone to use. I'll file a new ticket about implementing them.
