### ISSUE TITLE
[Bug] the icon of the frame doesn't get changed if you switch to another window in the frame

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#17]
STR:
1. open 2 taskspace windows and combine them into a single one so tab-bar appears.
2. put 2 different applications' windows into the same tab of a frame.
[the frame retains the icon of the first application that was added into the tab]
3. switch to the other application's window inside that tab

Expected result:
the icon in the tab bar of the frame should get changed to the icon of the second application's window.

Actual result:
the icon remains the same (matches the icon of the first application's window).

**Comment by cshnik** [comment]
Fixed in v0.1.5.3.

**Comment by Drugoy** [comment]
Seems to be generally fixed, yet I was able to reproduce the bug when I switched windows ~fast (actually, not very much fast, not like I used a script for that).
