### ISSUE TITLE
[FR] make each tab has the app icon

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#18]
Currently there's only one icon in the tab bar (at left) which is related to the active tab in the frame.
So you don't have visible representation of what windows are opened in the neighboring tabs.

What I suggest is to make the interface more like it is in browsers: each tab should have it's own favicon.

This will be extra comfortable if you have 1 application per 1 tab (since icons are not only buttons, but also are tiny indicators [that show what application is opened there] that make navigation between applications easier and faster).

**Comment by cshnik** [comment]
![explorerx4](https://cloud.githubusercontent.com/assets/8019354/4866647/b2fed202-612d-11e4-926b-5cd8eefe3c39.png)

Fixed in the 0.2.0.1.
