### ISSUE TITLE
[FR] change the icon of the frames on the Windows taskbar to indicate that it's an application inside of TaskSpace's frame

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#19]
Currently, the icon of the frame's window just copies the icon of the active tab's first application.
So if you have 2 notepad windows and 1 of them is inside the TaskSpace frame - you'll have just 2 similar windows on the task bar. I suggest to draw taskspace's mini-icon just above the icon of the active tab's active application.
Just to distinguish TaskSpace's windows from normal windows.

**Comment by cshnik** [comment]
Good idea!

**Comment by cshnik** [comment]
Fixed in v0.1.5.3.
