### ISSUE TITLE
[Bug] sometimes TS frame fails to copy an application's icon

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#20]
Example application is hh.exe (Windows built-in help files (*.chm) reader).
STR:
1. Open a few TS frames and combine them (so that tabs appear).
2. Open any valid *.chm file using Windows built-in util 'hh.exe'.
3. Add hh.exe's window to the TS frame.

Expected result:
1. The icon in the tab bar should be the same as hh.exe has.
2. That icon should also be used for the frame's window on Windows taskbar.

Actual result:
1. There's empty space on the place for icon in the tab-bar.
2. The frame's window on Windows taskbar has TaskSpace's application icon.

Another example is "Run" window (just hit "Win+R" hotkey to open that window) -  has a bit different (a bit more awkward) results.
Run the above STR with that window and get these actual results:
1. apart from the "Run" window the TS container gets some tiny square.
But: 2. the frame's window on Windows taskbar has the correct icon.

**Comment by cshnik** [comment]
Fixed in 0.2.0.0.
