### ISSUE TITLE
[FR] bring support of tabs drag'n'drop

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#26]
1. Drag'n'drop a tab out from container to
   either
     a). detach it into a separate container (i.e. into a 1-tabbed TS container)
   or
     b). release all of it's windows from a container at all (back to normal windows)
   and provide a setting to let the user choose preferred behavior.
2. Drag'n'drop a tab from one container into another (just in case you'd like re-organize meta-containers [TS windows]).

**Comment by cshnik** [comment]
Agreed.

**Comment by cshnik** [comment]
Fixed in v0.1.6.0.

**Comment by Drugoy** [comment]
Doesn't work if container has more than 1 window.

**Comment by Drugoy** [comment]
err, wait, it actually works.
