### ISSUE TITLE
[FR] add an option that would close all the windows for a tab you close

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#28]
It would be nice to have an option that would close a tab along together with the closure of all the windows that were in that tab.

This feature might be extra useful if it will be realized along with features like #27 and #29.

**Comment by cshnik** [comment]
Agreed.

**Comment by cshnik** [comment]
"Close All" feature added to v0.2.0.1.
The possible ways to execute it are:
- system menu option(right click on TaskSpace caption/Alt+Space)
- Alt+Ctrl+F4 hotkey
- Ctrl+click on Close(the most handy one)

**Comment by cshnik** [comment]
![taskspace-sysmenu-closeall](https://cloud.githubusercontent.com/assets/8019354/4848886/7deae48c-605d-11e4-9880-52f9dabbd855.png)

**Comment by Drugoy** [comment]
I think 'Close All' is too confusing: close all what? taskspace tabs? taskspace windows? current actuve taskspace tab and all the windows inside? all tabs and all the windows inside? all windows in the system?
