### ISSUE TITLE
[Bug][0.1.6.0] putting a WinExplorer's window into a container makes that container have transparent bar at bottom

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#32]
This bug appeared in v0.1.6.0 and happens in W7 with Aero theme and "native" selected in TaskSpace (btw, you forgot to rename "native" into russian, it still remains "без темы" instead of "Системная".

STR
1. just put any Windows Explorer's window into taskspace container and a transparent bar appears at bottom of the container.

**Comment by cshnik** [comment]
Fixed in the v0.1.6.1.
