### ISSUE TITLE
[FR] Add 16x16 TS icons to all it's menuitems injected into system context menus

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#36]
STR:
1. Open TS window.
2. Right click it's favicon (icon in the top left corner of the window).

Actual result:
<img src="https://i.imgur.com/Yy90sd1.png">

Expected result:
Those menuitems should have icons (the ones related to the menuitems' actions or just TaskSpace icons (new icon is quite nice).
Why?
Because some of other software, that user has running, may also add it's menuitems and it becomes quite hard to distringuish which menuitem does what and which program added it.

**Comment by cshnik** [comment]
I'm still not sure. Do you think this looks good?
![taskspace-sysmenu](https://cloud.githubusercontent.com/assets/8019354/4847745/3c0dee9a-6055-11e4-96f8-fe89ab3c6772.png)

**Comment by cshnik** [comment]
However, this menu looks much more natural:
![image](https://cloud.githubusercontent.com/assets/8019354/4848085/aca7e41a-6057-11e4-8651-f6016a0293e9.png)

**Comment by cshnik** [comment]
Fixed in the 0.2.0.1.

**Comment by Drugoy** [comment]
I would prefer as it looks on the topmost screenshot [I haven't yet tested 0.2.0.1].

**Comment by cshnik** [comment]
All these changes for menus were added to 0.2.0.1.
