### ISSUE TITLE
[Locale] rephrase a menuitem's text from "Windows Theme" to "Theme"

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#5]
Because currently it slightly confuses users: one might think that here you may switch the theme used in Windows OS, but in fact the menuitem changes only TaskSpace containers' appearance (and there's also no need to start every word with caps letter).

**Comment by cshnik** [comment]
"Container window's theme" is too long for me. How about plain "Theme"?

**Comment by Drugoy** [comment]
I'd suggest "Container theme" or "TaskSpace theme" or "Frame theme", since just "theme" may also be confusing (which one? maybe OS theme?).

**Comment by cshnik** [comment]
But in analogy "language" label is not confusing since we are working with the concrete application: TaskSpace.

**Comment by Drugoy** [comment]
Yeah, good point. You are right.

**Comment by cshnik** [comment]
Agreed. Rephrasing menu item's text to "Theme".

**Comment by cshnik** [comment]
Fixed in v0.1.5.3.
