### ISSUE TITLE
[Semi-functional] make counter in the frame's title never be higher than the number of currently opened frames

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#6]
Currently, you may open 3 container windows and then close them.
After that, if you open another container window it's title will be "TaskSpace4", although there are no other container windows.
I suggest to make that counter in the title always match the number of currently opened containers.

I also suggest to set low priority for this issue, since it's quite minor.

**Comment by cshnik** [comment]
Agreed.

**Comment by cshnik** [comment]
Fixed in v0.1.5.3.
