### ISSUE TITLE
[FR] make container retain the consumed window's size

### ISSUE THREAD

**Issue by Drugoy** [cshnik/TaskSpace#7]
The thing is that currently when you put a window into a container - it gets resized to fit container's size.

But I think it's better to make container fit the size of the consumed window (the one you added to the container) + the size for container window's title bar and borders, so the initial window stays the same size as it was before being put into a container.

**Comment by cshnik** [comment]
Not sure. I can't see the reason why TaskSpace should decrease by default(probably, this behavior can be optional). TaskSpace - is a container for attached windows and does not depends on its contents (in the global sense).

**Comment by Drugoy** [comment]
Well, the thing is I regard TaskSpace as... a service: you don't work with TaskSpace, you work with your programs, but in a different UI, provided by TaskSpace.

When you create a new TaskSpace window - it gets opened pretty small, so when you drop a huge (nearly full-screen) window into that container - personally I expect the container to expand to fit it's new contents, but instead I get my application's window shrunk into a tiny window, so I then have to re-assign position and size to make the window usable again.

Anyways, why not make this behavior optional? It's always nice to actually have a choice, rather than use hardcoded presets that you can't change.

**Comment by cshnik** [comment]
I don't want to start charging UI with multiple extremely small options, I think this may confuse some day.
Actually, registered version offers increased initial size of TaskSpace container:
800x600(registered) vs 400x300(unregistered).
I'll think about this later.

**Comment by Drugoy** [comment]
This issue is not about the small size of newly created frame. Even if you'd make default size for frames 1820 x 980 (which is almost FullHD) - there will be a backwards size problem: user puts a small window into a huge container and that window gets instantly blown into HUGE one.

Also, I've got another idea that I will describe now in a new ticket.

**Comment by cshnik** [comment]
In v0.2.0.1 there is a hotkey Ctrl+Shift+T which creates a new taskspace from active window(the size of new taskspace is adjusted to active window size).

**Comment by Drugoy** [comment]
Errr, this feature without #12 doesn't look much helpful and I'm sorry if I didn't make it clear that I see these two issues related.

The way you added it to 0.2.0.1 works only for the 1st window that gets into a TS container.
But TS containers are meant to have tabs and thus contain multiple windows.

The issue from my last comment here is still actual

> user puts a small window into a huge container and that window gets instantly blown into HUGE one.
